Repository computablee/DotMP, pull requests merged in 2023-10, with the labels that each got.

#53 Chore: Remove dead code
  DotMP-Tests/ParallelTests.cs
  DotMP/Exceptions.cs
  DotMP/Parallel.cs
Labels: hacktoberfest-accepted

#67 [testing] PR to get all-contributors working
  .all-contributorsrc
Labels: invalid

#81 Refactoring, tidying up codebase
  .gitignore
  DotMP/Init.cs
  DotMP/Iter.cs
  DotMP/Parallel.cs
  DotMP/Tasking.cs
Labels: refactor

#84 Dependabot groups and a PR template
  .github/PULL_REQUEST_TEMPLATE.md
  .github/dependabot.yml
Labels: CI/CD

#94 Worksharing-For Optimizations
  DotMP-Tests/ParallelTests.cs
  DotMP/DotMP.csproj
  DotMP/ForkedRegion.cs
  DotMP/Init.cs
  DotMP/Iter.cs
  DotMP/Parallel.cs
  DotMP/Wrappers.cs
  benchmarks/HeatTransfer/HeatTransfer.csproj
  benchmarks/HeatTransfer/Program.cs
  examples/CSParallel/KNN/KNN.sln
  examples/DotMP/KNN/KNN.sln
  examples/Serial/KNN/KNN.sln
Labels: bug, performance
